### ISSUE TITLE
block profile

### ISSUE THREAD

**Issue by dborsnich** [Villhellm/custom-sidebar#14]
Hi, thanks for your job!

Is it posible to block profile button?

If you refresh the web page (in a web browser)  appear for one second, all side bar icons and you can choosse them. This is a way to hack the restrictions. Is possible to don't show all items to avoid this?

Thanks!

**Comment by Villhellm** [comment]
This plugin does *not* block access to any Home Assistant features, it is purely for aesthetics and ease of use.

That said, the reason your icons are showing up when you refresh from the user profile page is because you probably did not follow through with the install instructions in the README https://github.com/Villhellm/custom-sidebar#step-2
